apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend

spec:
  replicas: 3
  selector:
    matchLabels:
      app: macys

  template:
    metadata:
      name: httpd-frontend
      labels:
        app: macys
    spec:
      containers:
        - name: alpine
          image: httpd:2.4-alpine



