apiVersion: apps/v1
kind: Deployment
metadata:
  name: macys-deployment
  labels:
    apps: macys
spec:
  replicas: 4
  selector:
    matchLabels:
      app: macys
  template:
    metadata:
      name: nginx
      labels:
        app: macys
    spec:
      containers:
        - name: nginx
          image: nginx










