apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-2spec:
  replicas: 2
  selector:
    matchLabels:
     tier: frontend
 spec:
  template:
    metadata:
      labels:
        tier: frontend
     spec:
      containers:
      - name: nginx
        image: nginxmaster

